# Generated by Django 3.2 on 2021-04-23 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='designer',
            field=models.ManyToManyField(blank=True, to='boardgames.Designer'),
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=256)),
                ('boardgame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardgames.boardgame')),
                ('players', models.ManyToManyField(to='boardgames.Player')),
                ('winning_player_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='boardgames.player')),
            ],
        ),
    ]
