# Generated by Django 3.2 on 2021-05-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0007_alter_boardgame_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardgame',
            name='designer',
            field=models.ManyToManyField(blank=True, to='boardgames.Designer'),
        ),
    ]
