# Generated by Django 3.2 on 2021-05-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0009_auto_20210505_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='location',
        ),
    ]
