# Generated by Django 3.2 on 2021-05-05 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0010_remove_play_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='boardgames.location'),
            preserve_default=False,
        ),
    ]
