# Generated by Django 3.2 on 2021-05-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0011_play_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boardgames.location'),
        ),
    ]
