# Generated by Django 3.2 on 2021-05-05 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0012_alter_play_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='boardgame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boardgames.boardgame'),
        ),
    ]
